---
title: "02 Supervised ML"
author: "Ahmad Nadeem Saigol"
date: "2020-11-05"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# Loading Libraries
```{r}
library(tidyverse)
library(parsnip)
library(recipes)
library(rsample)
library(yardstick)
library(tidymodels)
```

# Loading Data
```{r}
bike_features_tbl <- readRDS("new_raw_data/Business Decisions with Machine Learning/bike_features_tbl.rds") %>% 
  select(model:url, `Rear Derailleur`, `Shift Lever`)
```

# Build Model
```{r}
model <- linear_reg(mode = "regression") %>%
  set_engine("lm")
```

# Splitting
```{r}
split_obj <- rsample::initial_split(bike_features_tbl, prop   = 0.80, 
                                    strata = "category_2")

train_tbl <- training(split_obj)
test_tbl  <- testing(split_obj)

train_tbl <- train_tbl %>% set_names(str_replace_all(names(train_tbl), " |-", "_"))
test_tbl  <- test_tbl  %>% set_names(str_replace_all(names(test_tbl),  " |-", "_"))

```

# Feature Engineering

```{r}
bike_price_rec <- 
  
  recipe(price  ~ ., data = train_tbl %>% select(-c(model:weight), -category_1, -c(category_3:gender))) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  prep()
```

```{r}
train_transformed_tbl <- bake(bike_price_rec, new_data = NULL)
test_transformed_tbl  <- bake(bike_price_rec, new_data = test_tbl)
```
## Training dataset
```{r}
train_transformed_tbl %>% head()

```
## Test dataset
```{r}
test_transformed_tbl %>% head()
```

# Workflow

```{r}
bikes_wflow <- 
  workflow() %>% 
  add_model(model) %>% 
  add_recipe(bike_price_rec)
```
# Train
```{r}
bikes_fit <- 
  bikes_wflow %>% 
  fit(data = train_tbl)
```
# Prediction
```{r}
predict(bikes_fit, test_tbl) %>%
  bind_cols(test_tbl %>% select(price)) %>%
  yardstick::metrics(truth = price, estimate = .pred) 
```